### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by specing** [OpenNuvoton/M051BSP#1]
What license are these BSPs under? There is only the CMSIS agreement from ARM for the CMSIS part and "All rights reserved." at the top of text files, which probably makes this library legally unusable outside Nuvoton.

**Comment by wschang0** [comment]
Our BSP could be redistributed and used in connection with a Nuvoton microcontroller product.

**Comment by hank6213** [comment]
我們公司已經採購新唐M2351的MCU數顆，準備要開發產品用

**Comment by wschang0** [comment]
The license description has been added.
